name: "Build actions release"

on:
  workflow_dispatch:

env:
  # Adjust this to alter which branch to pull and build from. This is useful if wanting to deviate from the 
  # original marvinpinto/actions source code and implement manual changes that can be developed on a new branch.
  SOURCE_BRANCH: master

jobs:
  fetch-and-tag:
    name: "Build actions release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.SOURCE_BRANCH }}
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: |
          yarn workspace automatic-releases install --frozen-lockfile
          yarn workspace automatic-releases build

      - run: cp -r packages/automatic-releases/dist/ $GITHUB_WORKSPACE/
      - run: cp packages/automatic-releases/action.yml $GITHUB_WORKSPACE/

      - name: Commit files
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Workflow"
          git checkout stable
          git add dist action.yml
          git commit -m "Automatic release build"
          git push
